### ISSUE TITLE
angular-bootstrap-md + Angular 15

### ISSUE THREAD

**Issue by krabouilleur** [mdbootstrap/mdb-angular-ui-kit#158]
On Angular the 15 migration failed:
Package "angular-bootstrap-md" has an incompatible peer dependency to "@angular/cdk" (requires "^14.0.0", would install "15.1.0")

Is there a way to upgrade angular-bootstrap-md ?

I'm using bootstrap@5.2.0

**Comment by idzark** [comment]
If you want to use Bootstrap 5 you should install mdb-angular-ui-kit package (we added support for Angular 15 in v4.0.0).

angular-bootstrap-md is an older library that uses Bootstrap 4

**Comment by krabouilleur** [comment]
is there steps for migrate angular-bootstrap-md to mdb-angular-ui-kit ?

or is there not relation between this two packages ?

**Comment by idzark** [comment]
We tried to keep as many similarities as possible, but the mdb-angular-ui-kit is a new library, not a continuation of the angular-bootstrap-md.

But you can keep using angular-bootstrap-md if you don't want to switch to mdb-angular-ui-kit. We are already working on a new release with support for Angular 15 and it should be available in a few weeks. I just thought that you installed a wrong library because you mentioned Bootstrap 5 (angular-bootstrap-md is built with Bootstrap 4) and created the issue in mdb-angular-ui-kit repository. For issues related to angular-bootstrap-md please use this one: https://github.com/mdbootstrap/mdb4-angular-ui-kit
